name: SensorLibrary
main: org.redstonechips.sensorlibrary.SensorLibrary
version: 0.34
author: eisental
description: Sensor library for RedstoneChips integrated circuits plugin.
website: eisental.github.com/RedstoneChips
depend: [RedstoneChips]

