name: SensorLibrary
main: org.tal.sensorlibrary.SensorLibrary
version: 0.33t1
author: eisental
description: Sensor library for RedstoneChips integrated circuits plugin.
website: eisental.github.com/RedstoneChips
depend: [RedstoneChips]

